//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDo.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToDo 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        public static string CompletedItemsHeader {
            get {
                return ResourceManager.GetString("CompletedItemsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        public static string CompletedList {
            get {
                return ResourceManager.GetString("CompletedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定清除所有已完成条目？ 的本地化字符串。
        /// </summary>
        public static string DeleteCompletedItems {
            get {
                return ResourceManager.GetString("DeleteCompletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以后 的本地化字符串。
        /// </summary>
        public static string ExpandHeaderLater {
            get {
                return ResourceManager.GetString("ExpandHeaderLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string ExpandHeaderToday {
            get {
                return ResourceManager.GetString("ExpandHeaderToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明天 的本地化字符串。
        /// </summary>
        public static string ExpandHeaderTomorrow {
            get {
                return ResourceManager.GetString("ExpandHeaderTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意见反馈 的本地化字符串。
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容： 的本地化字符串。
        /// </summary>
        public static string FeedBackContentTitle {
            get {
                return ResourceManager.GetString("FeedBackContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来自ToDo的反馈意见 的本地化字符串。
        /// </summary>
        public static string FeedBackEmailSubject {
            get {
                return ResourceManager.GetString("FeedBackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yangchao294@hotmail.com 的本地化字符串。
        /// </summary>
        public static string FeedBackEmailTo {
            get {
                return ResourceManager.GetString("FeedBackEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感谢您使用我们的产品，如果您在使用过程中遇到任何的不便或建议和意见都欢迎您反馈给我们。 的本地化字符串。
        /// </summary>
        public static string FeedBackTitle {
            get {
                return ResourceManager.GetString("FeedBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string MessageBoxTip {
            get {
                return ResourceManager.GetString("MessageBoxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评分推荐 的本地化字符串。
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
    }
}
